- color: 0E8A16
  description: Exciting new Features.
  name: Feature
- color: b60205
  description: Emergency hotfix.
  name: emergency
- color: f9d0c4
  description: Refactor code.
  name: Refactoring
- color: d73a4a
  description: Simple fix for a non-critical issue.
  name: Bug
- color: 0075ca
  description: Add or update documentation.
  name: Documentation
- color: cfd3d7
  description: Setting and Maintenance.
  name: Maintenance
