changelog:
  exclude:
    labels:
      - ignore-for-release

  categories:
    - title: Exciting new Features. 🎉
      labels:
        - Feature
    - title: Emergency hotfix. 🚑
      labels:
        - Hotfix
    - title: Refactor code. ♻️
      labels:
        - Refactoring
    - title: Bugfix for a non-critical issue. 🩹
      labels:
        - Bug
    - title: Add or update documentation. 📑
      labels:
        - Documentation
    - title: Setting and Maintenance. 🔧
      labels:
        - Maintenance
    - title: Other Changes
      labels:
        - "*"
