name: Sync labels

on: pull_request
jobs:
  build:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      # label-syncerを使用

      - name: Run label-syncer
        uses: micnncim/action-label-syncer@v0.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yaml
